name: ci
on: pull_request
jobs:
  test-ray-client:
    continue-on-error: true
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.7", "3.8"]
        ray-version: ["1.3", "nightly"]
        retries: [1, 2, 3]
    env:
      MODIN_ENGINE: ray
      MODIN_MEMORY: 1000000000
      MODIN_RAY_CLUSTER: "True"
      TEST_RAY_CLIENT: "True"
    name: "test-ray-client (python ${{matrix.python-version}}, ray ${{matrix.ray-version}}, run #${{matrix.retries}})"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: modin
          python-version: ${{matrix.python-version}}
          channel-priority: strict
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - run: pip install -r requirements-dev.txt
      - run: pip install ray==1.3.0
        if: matrix.ray-version == '1.3'
      - run: pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
        if: matrix.python-version == '3.7' && matrix.ray-version == 'nightly'
      - run: pip install -U https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp38-cp38-manylinux2014_x86_64.whl
        if: matrix.python-version == '3.8' && matrix.ray-version == 'nightly'
      - name: Install HDF5
        run: sudo apt update && sudo apt install -y libhdf5-dev
      - run: MODIN_BENCHMARK_MODE=True pytest -x modin/pandas/test/internals/test_benchmark_mode.py
      - run: pytest -x modin/pandas/test/dataframe/test_iter.py
      # - run: pytest -x modin/pandas/test/dataframe/test_udf.py
      - run: pytest -x modin/pandas/test/dataframe/test_window.py
      - run: pytest -x modin/pandas/test/dataframe/test_pickle.py
      - run: pytest -x modin/pandas/test/test_rolling.py
      - run: pytest -x modin/pandas/test/test_concat.py
      - run: pytest -x modin/pandas/test/test_reshape.py
      - run: pytest -x modin/pandas/test/test_general.py
      - run: pytest -x modin/pandas/test/test_io.py