name: ci
on: pull_request
jobs:
  test-ray-client:
    continue-on-error: true
    timeout-minutes: 30
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.7", "3.8"]
        retries: [1,2,3,4,5]
    env:
      MODIN_ENGINE: ray
      MODIN_MEMORY: 1000000000
      MODIN_RAY_CLUSTER: "True"
      TEST_RAY_CLIENT: "True"
    name: test-ray-client (python ${{matrix.python-version}}, ${{matrix.retries}})
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: modin
          python-version: ${{matrix.python-version}}
          channel-priority: strict
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - run: pip install -r requirements-dev.txt
      - run: pip install ray==1.3
      - run: (echo import pandas; cat /usr/share/miniconda/envs/modin/lib/python${{matrix.python-version}}/site-packages/ray/__init__.py) > tmp.py
      - run: mv tmp.py /usr/share/miniconda/envs/modin/lib/python${{matrix.python-version}}/site-packages/ray/__init__.py
      - name: Install HDF5
        run: sudo apt update && sudo apt install -y libhdf5-dev
      - run: MODIN_BENCHMARK_MODE=True pytest modin/pandas/test/internals/test_benchmark_mode.py
      - run: pytest modin/pandas/test/dataframe/test_iter.py
      - run: pytest modin/pandas/test/dataframe/test_udf.py
      - run: pytest modin/pandas/test/dataframe/test_window.py
      - run: pytest modin/pandas/test/dataframe/test_pickle.py
      - run: pytest modin/pandas/test/test_rolling.py
      - run: pytest modin/pandas/test/test_concat.py
      - run: pytest modin/pandas/test/test_reshape.py
      - run: pytest modin/pandas/test/test_general.py
      - run: pytest modin/pandas/test/test_io.py